# Задачи в Питоне

# Задача 1 

Как найти евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу?

In [2]:
import pandas as pd
import numpy as np
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])

In [3]:
distance = np.sqrt(np.sum((a-b)**2))

print(distance)

2.0


# Задача 2

Как найти максимально возможное абсолютное значение корреляции каждого столбца с другими столбцами в df?

In [8]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(1, 100, 16).reshape(4, 4), columns=list('efgh'), index=list('abcd'))
corr_matrix = df.corr()
max_corr = corr_matrix.abs().max()
print(max_corr)

e    1.0
f    1.0
g    1.0
h    1.0
dtype: float64


# Задача 3

Как нормализовать все столбцы в DataFrame?

Нормализуйте все столбцы df путём вычитания среднего значения столбца и деления на стандартное отклонение.
Сделайте так, чтобы все значения в df находились в диапазоне от 0 до 1.

df = pd.DataFrame(np.random.randint(1, 100, 16).reshape(4, 4))

In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame(np.random.randint(1, 100, 16).reshape(4, 4))

scaler = MinMaxScaler()
df_norm = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

print(df_norm)

          0         1         2         3
0  1.000000  0.069767  0.000000  0.652778
1  0.790698  0.395349  0.942308  0.541667
2  0.000000  0.000000  0.923077  0.000000
3  0.372093  1.000000  1.000000  1.000000


# Задача 4

Как объединить два DataFrame по двум столбцам так, чтобы остались только общие строки?

Объедините df1 и df2 по столбцам fruit-frukt и weight-ves.

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['low', 'medium', 'high'] * 3,
                    'price': np.random.randint(0, 100, 9)})

df2 = pd.DataFrame({'frukt': ['apple', 'banana', 'melon'] * 2,
                    'ves': ['low', 'high'] * 3,
                    'price': np.random.randint(0, 100, 6)})

In [14]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['low', 'medium', 'high'] * 3,
                    'price': np.random.randint(0, 100, 9)})

df2 = pd.DataFrame({'frukt': ['apple', 'banana', 'melon'] * 2,
                    'ves': ['low', 'high'] * 3,
                    'price': np.random.randint(0, 100, 6)})

df_merged = pd.merge(df1, df2, left_on=['fruit', 'weight'], right_on=['frukt', 'ves'], how='inner')

print(df_merged)

   fruit weight  price_x  frukt  ves  price_y
0  apple    low       34  apple  low       48
1  apple    low       25  apple  low       48
2  apple    low       77  apple  low       48


# Задача 5

Как узнать частоту уникальных значений во всём DataFrame?

Ввод:

df = pd.DataFrame(np.random.randint(1, 10, 16).reshape(4, 4), columns=list('abcd'))

In [15]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(1, 10, 16).reshape(4, 4), columns=list('abcd'))

value_counts = pd.concat([df[col].value_counts() for col in df.columns]).reset_index()
value_counts.columns = ['value', 'count']

print(value_counts)

    value  count
0       3      2
1       2      1
2       6      1
3       8      2
4       3      1
5       1      1
6       3      1
7       6      1
8       5      1
9       4      1
10      7      1
11      5      1
12      6      1
13      8      1


# Задача 6

Как создать новый столбец, который содержит номера ближайших по евклидовому расстоянию столбцов?

In [17]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

df = pd.DataFrame(np.random.randint(1, 100, 16).reshape(4, 4), columns=list('efgh'), index=list('abcd'))

distances = pdist(df.T, metric='euclidean')

dist_matrix = squareform(distances)

closest_cols = dist_matrix.argsort(axis=1)[:, 1]

df['closest'] = closest_cols

print(df)

    e   f   g   h  closest
a  88   2  55   1        1
b  99  73  13  16        3
c  82  71  42  47        3
d  75  63  35  18        2


# Задача 7

Как поменять местами две строки в двумерном массиве NumPy? Поменяйте местами строки 1 и 3 массива a.

In [21]:
a = np.arange(9).reshape(3,3)  
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Задача 8

Как найти количество уникальных значений в массиве NumPy? Найдите уникальные значения и их количество в столбце species таблицы iris.

In [22]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

species = iris[:, -1]

unique_species, counts = np.unique(species, return_counts=True)

print(unique_species)
print(counts)

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']
[50 50 50]


# Задача 9

Как найти второе максимальное значение в массиве, который сгруппирован по другому массиву? Найдите значение второго самого длинного petallength вида setosa в таблице iris.

In [23]:
setosa_petal_lengths = iris[iris[:, 4] == b'Iris-setosa'][:, 2].astype(float)
setosa_petal_lengths_sorted = np.sort(setosa_petal_lengths)[::-1]
second_largest_setosa_petal_length = setosa_petal_lengths_sorted[1]

print("Второе самое длинное petallength вида setosa: ", second_largest_setosa_petal_length)

Второе самое длинное petallength вида setosa:  1.9


# Задача 10

Как отранжировать элементы массива NumPy?
a = np.random.randint(100, size=10)
print(a)
[9 15 64 28 89 93 29 8 73 0]

In [25]:
idx = np.argsort(a)
ranked_a = a[idx]
print(ranked_a)
# [ 0  8  9 15 28 29 64 73 89 93]

[ 8 12 20 28 30 31 48 55 77 80]


In [26]:
a = np.random.randint(100, size=10)

# Решение
print(a.argsort().argsort())

[0 5 9 6 3 7 1 8 4 2]


# Задача 11

Как найти результат деления минимального значения на максимальное в каждой строке двумерного массива? 
np.random.seed(10)
a = np.random.randint(1, 10, [3, 3])
a
array([[5, 1, 2],
[1, 2, 9],
[1, 9, 7]])

In [28]:
import numpy as np

np.random.seed(10)
a = np.random.randint(1, 10, [3, 3])

result = np.min(a, axis=1) / np.max(a, axis=1)
print(result)

[0.2        0.11111111 0.11111111]


# Задача 12

Как найти повторяющиеся значения в массиве NumPy? Найдите повторяющиеся значения (начиная со второго вхождения) в заданном массиве и отметьте их как True. Первое вхождение отмечайте как False.
np.random.seed(10)
a = np.random.randint(0, 7, 10)

In [32]:
import numpy as np

np.random.seed(10)
a = np.random.randint(0, 7, 10)

unique_vals, counts = np.unique(a, return_counts=True)

repeated_vals = np.full(a.shape[0], False)
repeated_vals[np.where(counts > 1)[0][1:]] = True

print(repeated_vals)

[False  True False  True  True False False False False False]


# Задача 13

Как удалить из массива NumPy строки, которые содержат nan?

In [35]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_1 = iris[~np.isnan(iris).any(axis=1)]
print(iris_1)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.

# Задача 14

Как сделать left join двух объектов datatable.Frame? Объедините заданные объекты по ключу А.

In [45]:
!pip install datatable
import datatable as dt

df1 = dt.Frame(A=[1, 2, 3, 4], B=['a', 'b', 'c', 'd'])
df2 = dt.Frame(A=[1, 2, 3, 4, 5], C=['a2', 'b2', 'c2', 'd2', 'e2'])

merged = df1.merge(df2, how='left', on='A')
print(merged)

  Using cached datatable-1.0.0.tar.gz (1.1 MB)
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Building extension _datatable
      Build directory = 'build/build'
      Created directory 'build/build'
      Destination directory = 'src/datatable/lib'
      Added 309 source files from pattern src/core/**/*.cc: ['src/core/writebuf.cc', 'src/core/set_funcs.cc', 'src/core/py_encodings.cc', 'src/core/cstring.cc', 'src/core/column.cc', 'src/core/py_buffers.cc', 'src/core/groupby.cc', 'src/core/sort_insert.cc', 'src/core/stype.cc', 'src/core/api.cc', 'src/core/buffer.cc', 'src/core/rowindex_slice.cc', 'src/core/stats.cc', 'src/core/mmm.cc', 'src/core/call_logger.cc', 'src/core/rowindex_array.cc', 'src/core/sort.cc', 'src/core/rowindex.cc', 'src/core/column_from_python.cc', 'src/core/options.c

ModuleNotFoundError: No module named 'datatable'